create TABLE FW_MIG_ENTITY_COLUMNS (
		ID VARCHAR(100),
			TABLE_NAME VARCHAR(100),
				COLUMN_NAME VARCHAR(100),
					ORDINAL_POSITION NUMBER(38,0),
						DATA_TYPE VARCHAR(100),
							CHARACTER_MAXIMUM_LENGTH NUMBER(38,0)
						);
